/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_assignment;

import final_assignment.admin_receipt;
import final_assignment.admin_main;
import final_assignment.admin;
import final_assignment.admin_top_up;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.*;
import java.util.*;

public class admin_user_reg extends javax.swing.JFrame {

    /**
     * Creates new form admin_main
     */
    public admin_user_reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        urmenubar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_user_reg = new javax.swing.JButton();
        btn_top_up = new javax.swing.JButton();
        btn_receipt = new javax.swing.JButton();
        urinput = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_userid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbo_user_role = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tf_user_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_pswd = new javax.swing.JPasswordField();
        crud = new javax.swing.JPanel();
        btn_create = new javax.swing.JButton();
        btn_display = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 249, 244));

        urmenubar.setBackground(new java.awt.Color(151, 214, 207));
        urmenubar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Admin");

        btn_user_reg.setBackground(new java.awt.Color(255, 249, 244));
        btn_user_reg.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_user_reg.setForeground(new java.awt.Color(0, 102, 102));
        btn_user_reg.setText("User Reg.");
        btn_user_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_regActionPerformed(evt);
            }
        });

        btn_top_up.setBackground(new java.awt.Color(255, 249, 244));
        btn_top_up.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_top_up.setForeground(new java.awt.Color(0, 102, 102));
        btn_top_up.setText("Top Up");
        btn_top_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_top_upActionPerformed(evt);
            }
        });

        btn_receipt.setBackground(new java.awt.Color(255, 249, 244));
        btn_receipt.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_receipt.setForeground(new java.awt.Color(0, 102, 102));
        btn_receipt.setText("Receipt");
        btn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout urmenubarLayout = new javax.swing.GroupLayout(urmenubar);
        urmenubar.setLayout(urmenubarLayout);
        urmenubarLayout.setHorizontalGroup(
            urmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_user_reg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_top_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_receipt)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        urmenubarLayout.setVerticalGroup(
            urmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(urmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(urmenubarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(urmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_user_reg)
                            .addComponent(btn_top_up)
                            .addComponent(btn_receipt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        urinput.setBackground(new java.awt.Color(211, 235, 232));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("User ID :");

        tf_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_useridActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("User Role :");

        cbo_user_role.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cbo_user_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "customer", "vendor", "runner" }));
        cbo_user_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_user_roleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("User Name :");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Password :");

        javax.swing.GroupLayout urinputLayout = new javax.swing.GroupLayout(urinput);
        urinput.setLayout(urinputLayout);
        urinputLayout.setHorizontalGroup(
            urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urinputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(urinputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(urinputLayout.createSequentialGroup()
                        .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)))
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_user_name)
                    .addComponent(cbo_user_role, 0, 108, Short.MAX_VALUE)
                    .addComponent(tf_userid)
                    .addComponent(pf_pswd))
                .addContainerGap())
        );
        urinputLayout.setVerticalGroup(
            urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urinputLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cbo_user_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(urinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pf_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        crud.setBackground(new java.awt.Color(211, 235, 232));

        btn_create.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_display.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_display.setText("Display");
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crudLayout = new javax.swing.GroupLayout(crud);
        crud.setLayout(crudLayout);
        crudLayout.setHorizontalGroup(
            crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        crudLayout.setVerticalGroup(
            crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_back.setFont(new java.awt.Font("Tw Cen MT", 2, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urmenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_back)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(urmenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // MENU BAR
    private void btn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiptActionPerformed
        // lead to the admin_receipt
        admin_receipt receiptFrame = new admin_receipt();
        receiptFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_receiptActionPerformed

    private void btn_user_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_regActionPerformed
        // lead to the admin_user_reg 
        admin_user_reg userRegFrame = new admin_user_reg();
        userRegFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_user_regActionPerformed

    private void btn_top_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_top_upActionPerformed
        // lead to the admin_top_up
        admin_top_up topUpFrame = new admin_top_up();
        topUpFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_top_upActionPerformed

    
    //CRUD
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // update logic
        String userID = tf_userid.getText().trim();
        String newPassword = new String (pf_pswd.getPassword()).trim();
        String newName = tf_user_name.getText().trim();
        
        if (userID.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User ID is required.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        // Treat empty fields as null for optional updates
        
        if (newPassword.isEmpty()) newPassword = null;
        if (newName.isEmpty()) newName = null;
        
        admin adminInstance = new admin();
        boolean isUpdated = adminInstance.updateUser("users.txt", userID, newPassword, newName);
        
        if (isUpdated)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);        
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User ID not found. Update failed.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // to create a user
        // getting the user input from the jframe to put into the createUser function
        String userID = tf_userid.getText();
        String userName = tf_user_name.getText();
        String userRole = (String) cbo_user_role.getSelectedItem();
        char[] passwordArray = pf_pswd.getPassword();
        String userPswd = new String (passwordArray);
        
        //validating input
        if (userID.isEmpty()|| userName.isEmpty()|| userPswd.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;        
        }
        
        // call the create user from admin class
        try {
            admin adminInstance = new admin(userID, userPswd, userRole, userName); // Assuming admin class has a default constructor
            boolean isUserCreated = adminInstance.createUser1(userID, userPswd, userRole, userName);
            
            if (isUserCreated) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "User created successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Clear input fields after saving
                tf_userid.setText("");
                tf_user_name.setText("");
                pf_pswd.setText("");
                cbo_user_role.setSelectedIndex(0);    
            }
            
            else 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to create user. Check user ID and role.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error creating user: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }  
        
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // delete user button
        String chosen_user_id = tf_userid.getText().trim();
        
        if (chosen_user_id.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a User ID.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;        
        }
        
        // create an instance of admin class
        admin adminInstance = new admin();
        boolean isDeleted = adminInstance.deleteUser(chosen_user_id);
        if (isDeleted) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found. Deletion failed.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);        
        }
        
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tf_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_useridActionPerformed

    private void cbo_user_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_user_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_user_roleActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // back button lead to admin main frame
        admin_main adminMainFrame = new admin_main();
        adminMainFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
    
        String chosen_user_id = tf_userid.getText().trim();
        // create an instance of admin 
        admin adminInstance = new admin ();
        String userDetails = adminInstance.readUser("users.txt", chosen_user_id);
        javax.swing.JOptionPane.showMessageDialog(this, userDetails, "User Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btn_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_user_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_back;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_display;
    private javax.swing.JButton btn_receipt;
    private javax.swing.JButton btn_top_up;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_user_reg;
    private javax.swing.JComboBox<String> cbo_user_role;
    private javax.swing.JPanel crud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pf_pswd;
    private javax.swing.JTextField tf_user_name;
    private javax.swing.JTextField tf_userid;
    private javax.swing.JPanel urinput;
    private javax.swing.JPanel urmenubar;
    // End of variables declaration//GEN-END:variables
}
