/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_assignment;

import final_assignment.admin_top_up;
//import groupassignment.admin_receipt;
//import groupassignment.admin_user_reg;
import final_assignment.admin_receipt;
import final_assignment.admin_user_reg;

/**
 *
 * @author asus
 */
public class admin_main extends javax.swing.JFrame {

    /**
     * Creates new form admin_main
     */
    public admin_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        mainmenubar = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        btn_user_reg = new javax.swing.JButton();
        btn_top_up = new javax.swing.JButton();
        btn_receipt = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 249, 244));

        mainmenubar.setBackground(new java.awt.Color(151, 214, 207));
        mainmenubar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        admin.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 102, 102));
        admin.setText("Admin");

        btn_user_reg.setBackground(new java.awt.Color(255, 249, 244));
        btn_user_reg.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_user_reg.setForeground(new java.awt.Color(0, 102, 102));
        btn_user_reg.setText("User Reg.");
        btn_user_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_regActionPerformed(evt);
            }
        });

        btn_top_up.setBackground(new java.awt.Color(255, 249, 244));
        btn_top_up.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_top_up.setForeground(new java.awt.Color(0, 102, 102));
        btn_top_up.setText("Top Up");
        btn_top_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_top_upActionPerformed(evt);
            }
        });

        btn_receipt.setBackground(new java.awt.Color(255, 249, 244));
        btn_receipt.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_receipt.setForeground(new java.awt.Color(0, 102, 102));
        btn_receipt.setText("Receipt");
        btn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainmenubarLayout = new javax.swing.GroupLayout(mainmenubar);
        mainmenubar.setLayout(mainmenubarLayout);
        mainmenubarLayout.setHorizontalGroup(
            mainmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin)
                .addGap(18, 18, 18)
                .addComponent(btn_user_reg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_top_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_receipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainmenubarLayout.setVerticalGroup(
            mainmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin)
                    .addGroup(mainmenubarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(mainmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_user_reg)
                            .addComponent(btn_top_up)
                            .addComponent(btn_receipt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_logout.setBackground(new java.awt.Color(151, 214, 207));
        btn_logout.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(0, 102, 102));
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final_assignment/logo150.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainmenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_logout)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainmenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiptActionPerformed
        // lead to the admin_receipt
        admin_receipt receiptFrame = new admin_receipt();
        receiptFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_receiptActionPerformed

    private void btn_user_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_regActionPerformed
        // lead to the admin_user_reg 
        admin_user_reg userRegFrame = new admin_user_reg();
        userRegFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_user_regActionPerformed

    private void btn_top_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_top_upActionPerformed
        // lead to the admin_top_up
        admin_top_up topUpFrame = new admin_top_up();
        topUpFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_top_upActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // log out and lead to log in
        login loginframe = new login();
        loginframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_main().setVisible(true);      }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_receipt;
    private javax.swing.JButton btn_top_up;
    private javax.swing.JButton btn_user_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainmenubar;
    // End of variables declaration//GEN-END:variables
}
