/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_assignment;
import final_assignment.dataloader;
import final_assignment.admin;
import final_assignment.admin_main;
import final_assignment.admin_receipt;
import final_assignment.admin_user_reg;
import final_assignment.wallet;
import java.io.*;
import java.util.*;
public class admin_top_up extends javax.swing.JFrame {

    /**
     * Creates new form admin_main
     */
    public admin_top_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpmenubar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_user_reg = new javax.swing.JButton();
        btn_top_up = new javax.swing.JButton();
        btn_receipt = new javax.swing.JButton();
        btn_back = new javax.swing.JRadioButton();
        userinput = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_userid = new javax.swing.JTextField();
        btn_topup = new javax.swing.JButton();
        btn_update = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 249, 244));

        tpmenubar.setBackground(new java.awt.Color(151, 214, 207));
        tpmenubar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Admin");

        btn_user_reg.setBackground(new java.awt.Color(255, 249, 244));
        btn_user_reg.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_user_reg.setForeground(new java.awt.Color(0, 102, 102));
        btn_user_reg.setText("User Reg.");
        btn_user_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_regActionPerformed(evt);
            }
        });

        btn_top_up.setBackground(new java.awt.Color(255, 249, 244));
        btn_top_up.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_top_up.setForeground(new java.awt.Color(0, 102, 102));
        btn_top_up.setText("Top Up");
        btn_top_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_top_upActionPerformed(evt);
            }
        });

        btn_receipt.setBackground(new java.awt.Color(255, 249, 244));
        btn_receipt.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_receipt.setForeground(new java.awt.Color(0, 102, 102));
        btn_receipt.setText("Receipt");
        btn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpmenubarLayout = new javax.swing.GroupLayout(tpmenubar);
        tpmenubar.setLayout(tpmenubarLayout);
        tpmenubarLayout.setHorizontalGroup(
            tpmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_user_reg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_top_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_receipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tpmenubarLayout.setVerticalGroup(
            tpmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(tpmenubarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(tpmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_user_reg)
                            .addComponent(btn_top_up)
                            .addComponent(btn_receipt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_back.setFont(new java.awt.Font("Tw Cen MT", 2, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        userinput.setBackground(new java.awt.Color(211, 235, 232));
        userinput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("User ID : ");

        tf_userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_useridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userinputLayout = new javax.swing.GroupLayout(userinput);
        userinput.setLayout(userinputLayout);
        userinputLayout.setHorizontalGroup(
            userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinputLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        userinputLayout.setVerticalGroup(
            userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(userinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_topup.setBackground(new java.awt.Color(151, 214, 207));
        btn_topup.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_topup.setText("Top Up");
        btn_topup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_topupActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(151, 214, 207));
        btn_update.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_update.setText("Update User Balance");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tpmenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_topup)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btn_back))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(userinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_update))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpmenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(userinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_topup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // menu bar
    private void btn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiptActionPerformed
        // lead to the admin_receipt
        admin_receipt receiptFrame = new admin_receipt();
        receiptFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_receiptActionPerformed

    private void btn_user_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_regActionPerformed
        // lead to the admin_user_reg 
        admin_user_reg userRegFrame = new admin_user_reg();
        userRegFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_user_regActionPerformed

    private void btn_top_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_top_upActionPerformed
        // lead to the admin_top_up
        admin_top_up topUpFrame = new admin_top_up();
        topUpFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_top_upActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // back button lead to admin main frame
        admin_main adminMainFrame = new admin_main();
        adminMainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void tf_useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_useridActionPerformed

    // top up button
    private void btn_topupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_topupActionPerformed
        // topup (userID, topupamount, walletFile, userFile)
        String chosen_user_id = tf_userid.getText().trim();
        
        if (chosen_user_id.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User ID is required.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;              
        }
        
        admin adminInstance = new admin();
        boolean isTopUpDone = adminInstance.topup(chosen_user_id, "wallet.txt", "top_up.txt", "the_customer_order_history.txt");
        
        if (isTopUpDone)
        {
            try 
            {
                // get the updated wallet ballance
                ArrayList <wallet> walletList = dataloader.loadwallet("wallet.txt");
                double currentBalance = 0.0;
            
                for(int i = walletList.size() - 1; i >=0 ; i--)
                {
                    wallet w = walletList.get(i);
                    if (w.getUser_id().equals(chosen_user_id))
                    {
                        currentBalance = w.getCurrent_balance();
                        break;
                    }
                }
            
                javax.swing.JOptionPane.showMessageDialog(this, "Top-up has been successful! Notif. has been sent to customer! \n" + 
                                                          "Customer ID: " + chosen_user_id + "\n" + 
                                                          "Current Balance: " + currentBalance, 
                                                          "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);          
            }
            catch (IOException e)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error reading the wallet file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();    
            }
        }
        
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "No top-up request with status 'placed' for user ID", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);        
        }

    }//GEN-LAST:event_btn_topupActionPerformed

    // if cancellation occurs, then update user balance
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String chosen_user_id = tf_userid.getText().trim();
        
        if (chosen_user_id.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User ID is required.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        admin adminInstance = new admin();
        boolean isUpdateDone = adminInstance.updateBalance(chosen_user_id, "wallet.txt", "top_up.txt","the_customer_order_history.txt");
        
        if (isUpdateDone)
        {
            try 
            {
                // get the updated wallet ballance
                ArrayList <wallet> walletList = dataloader.loadwallet("wallet.txt");
                double currentBalance = 0.0;
            
                for(int i = walletList.size() - 1; i >=0 ; i--)
                {
                    wallet w = walletList.get(i);
                    if (w.getUser_id().equals(chosen_user_id))
                    {
                        currentBalance = w.getCurrent_balance();
                        break;
                    }
                }
            
                javax.swing.JOptionPane.showMessageDialog(this, "Top-up has been successful! Notif. has been sent to customer! \n" + 
                                                          "Customer ID: " + chosen_user_id + "\n" + 
                                                          "Current Balance: " + currentBalance, 
                                                          "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);             
            }
            catch (IOException e) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error reading the wallet file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();                
            }
        }
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "No update balance request with status 'cancelled' for user ID", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);                
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_top_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_top_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_back;
    private javax.swing.JButton btn_receipt;
    private javax.swing.JButton btn_top_up;
    private javax.swing.JButton btn_topup;
    private javax.swing.JToggleButton btn_update;
    private javax.swing.JButton btn_user_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_userid;
    private javax.swing.JPanel tpmenubar;
    private javax.swing.JPanel userinput;
    // End of variables declaration//GEN-END:variables
}
