/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_assignment;

import final_assignment.admin_main;
import final_assignment.wallet;
import final_assignment.admin;
import final_assignment.admin_top_up;
import final_assignment.admin_user_reg;
import java.util.List; // For List
import javax.swing.table.DefaultTableModel; // For DefaultTableModel
import java.util.Objects; // For Objects
import java.io.IOException; // For IOException

public class admin_receipt extends javax.swing.JFrame {

    /**
     * Creates new form admin_main
     */
    public admin_receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        receiptmenubar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_user_reg = new javax.swing.JButton();
        btn_top_up = new javax.swing.JButton();
        btn_receipt = new javax.swing.JButton();
        btn_back = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_userid = new javax.swing.JTextField();
        btn_generate = new javax.swing.JButton();
        sp_transaction = new javax.swing.JScrollPane();
        table_transactions = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 249, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(417, 300));

        receiptmenubar.setBackground(new java.awt.Color(151, 214, 207));
        receiptmenubar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Admin");

        btn_user_reg.setBackground(new java.awt.Color(255, 249, 244));
        btn_user_reg.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_user_reg.setForeground(new java.awt.Color(0, 102, 102));
        btn_user_reg.setText("User Reg.");
        btn_user_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_regActionPerformed(evt);
            }
        });

        btn_top_up.setBackground(new java.awt.Color(255, 249, 244));
        btn_top_up.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_top_up.setForeground(new java.awt.Color(0, 102, 102));
        btn_top_up.setText("Top Up");
        btn_top_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_top_upActionPerformed(evt);
            }
        });

        btn_receipt.setBackground(new java.awt.Color(255, 249, 244));
        btn_receipt.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_receipt.setForeground(new java.awt.Color(0, 102, 102));
        btn_receipt.setText("Receipt");
        btn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receiptmenubarLayout = new javax.swing.GroupLayout(receiptmenubar);
        receiptmenubar.setLayout(receiptmenubarLayout);
        receiptmenubarLayout.setHorizontalGroup(
            receiptmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_user_reg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_top_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_receipt)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        receiptmenubarLayout.setVerticalGroup(
            receiptmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptmenubarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receiptmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(receiptmenubarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(receiptmenubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_user_reg)
                            .addComponent(btn_top_up)
                            .addComponent(btn_receipt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_back.setFont(new java.awt.Font("Tw Cen MT", 2, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(211, 235, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(242, 111));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("User ID :");

        btn_generate.setBackground(new java.awt.Color(151, 214, 207));
        btn_generate.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        btn_generate.setForeground(new java.awt.Color(0, 102, 102));
        btn_generate.setText("Generate Transaction Receipt");
        btn_generate.setToolTipText("");
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_generate)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Txn Amount", "Txn ID", "Txn Type", "Current Balance"
            }
        ));
        sp_transaction.setViewportView(table_transactions);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(sp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(receiptmenubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receiptmenubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(sp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_back)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiptActionPerformed
        // lead to the admin_receipt
        admin_receipt receiptFrame = new admin_receipt();
        receiptFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_receiptActionPerformed

    private void btn_user_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_regActionPerformed
        // lead to the admin_user_reg 
        admin_user_reg userRegFrame = new admin_user_reg();
        userRegFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_user_regActionPerformed

    private void btn_top_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_top_upActionPerformed
        // lead to the admin_top_up
        admin_top_up topUpFrame = new admin_top_up();
        topUpFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_top_upActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // back button lead to admin main frame
        admin_main adminMainFrame = new admin_main();
        adminMainFrame.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed
        // to generate transaction id
        String chosen_user_id = tf_userid.getText().trim();
        if (chosen_user_id.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "User ID is required.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;        
        }
        
        admin adminInstance = new admin();
        try 
        {
            List <wallet> transactions = adminInstance.getUserTransactions(chosen_user_id, "wallet.txt");
            if (transactions.isEmpty()) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "No transactions found for the given User ID.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            String [] columnNames = {"User ID", "Txn Amount", "Txn ID", "Txn Type", "Current Balance"};
            DefaultTableModel tableModel = new DefaultTableModel (columnNames, 0);
            
            for (wallet w : transactions)
            {
                Object [] rowData = 
                {
                    w.getUser_id(), w.getTransaction_amount(), w.getTransaction_id(),
                    w.getTransaction_type(), w.getCurrent_balance()
                };
                tableModel.addRow (rowData);
            }
            
            table_transactions.setModel(tableModel);
            sp_transaction.setVisible(true);
            
            
        }
        catch (IOException e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Error reading the wallet file.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } 
        
    }//GEN-LAST:event_btn_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_back;
    private javax.swing.JButton btn_generate;
    private javax.swing.JButton btn_receipt;
    private javax.swing.JButton btn_top_up;
    private javax.swing.JButton btn_user_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel receiptmenubar;
    private javax.swing.JScrollPane sp_transaction;
    private javax.swing.JTable table_transactions;
    private javax.swing.JTextField tf_userid;
    // End of variables declaration//GEN-END:variables
}
