/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package final_assignment;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class reorder extends javax.swing.JFrame {
    public String selected_item;
    public String order_id;
    public String user_id;
    public double item_price;
    
    ArrayList<customer_order_history> customerorderhistorylist = new ArrayList<>();
    ArrayList<menu> menu_items = new ArrayList<>();
    ArrayList<order> orderlist = new ArrayList<>();
    ArrayList<wallet> transactions = new ArrayList<>();
    ArrayList<vendor_order_history> vendorhistory = new ArrayList<>();
    ArrayList<holduserdata> helduserlist = new ArrayList<>();
    /**
     * Creates new form reorder
     */
    public reorder() {
        initComponents();
        
        //get logged in user id
        try{
            helduserlist = dataloader.loadheldusers("holduserdata.txt");
            
            for (holduserdata heldusers : helduserlist)
            {
                user_id = heldusers.getUserId();
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        //get order id for logged in users
        try
        {
            customerorderhistorylist = dataloader.loadcustomerorderhistory("the_customer_order_history.txt");            
            ArrayList<customer_order_history> filtered_order_id = new ArrayList<>();           
            for (customer_order_history order_history : customerorderhistorylist)
            {
                if (order_history.getUser_id().equals(user_id))
                {
                    filtered_order_id.add(order_history);
                }                
            }            
            for (customer_order_history ids : filtered_order_id)
            {                
                cboorderid.addItem(ids.getOrder_id());
            }            
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        //action listner
        cboorderid.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            order_id = cboorderid.getSelectedItem().toString();
        }
        });
        
        //get item name
        try
        {
            customerorderhistorylist = dataloader.loadcustomerorderhistory("the_customer_order_history.txt");
            for (customer_order_history order_history : customerorderhistorylist)
            {
                if (order_history.getOrder_id().equalsIgnoreCase(order_id))
                {
                    selected_item = order_history.getItem_name();
                }
                
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        //get item price
        try
        {
            menu_items = dataloader.loadmenuitems("themenu.txt");
            for (menu item : menu_items)
            {
                if (item.getItem_name().equalsIgnoreCase(selected_item))
                        {
                            item_price = item.getItem_price();
                        }
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblshow = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboorderid = new javax.swing.JComboBox<>();
        btnshow = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 249, 224));

        tblshow.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        tblshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Item Name", "Delivery Option", "Total Bill"
            }
        ));
        jScrollPane1.setViewportView(tblshow);

        jPanel2.setBackground(new java.awt.Color(151, 214, 207));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel1.setText("Reorder");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(151, 214, 207));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jLabel2.setText("Order ID:");

        cboorderid.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N

        btnshow.setBackground(new java.awt.Color(255, 249, 224));
        btnshow.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btnshow.setText("Show");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnorder.setBackground(new java.awt.Color(255, 249, 224));
        btnorder.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btnorder.setText("Order");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 249, 224));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 249, 224));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jButton5.setText("Top Up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboorderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnshow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnorder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        try
        {
            customerorderhistorylist = dataloader.loadcustomerorderhistory("the_customer_order_history.txt");
            DefaultTableModel model = (DefaultTableModel) tblshow.getModel();
            model.setRowCount(0);
            
            
            for (customer_order_history order_history : customerorderhistorylist)
            {
                if (order_history.getOrder_id().equalsIgnoreCase(order_id) && order_history.getUser_id().equalsIgnoreCase(user_id))
                {
                    model.addRow(new Object[] {order_history.getItem_name(), order_history.getOrder_type(), order_history.getOrder_amount()});
                }
            }
        }catch (IOException ex) {
                System.out.println("Error writing to file: " + ex.getMessage());
                    }
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        //order & transaction ID
        String new_order_id = order.generateOrderID();
        String transaction_id = order.generatetransactionID();
        
        
        //calculate time and date
        String time = order.writerealtime() +" "+ order.writerealdate();
        
        //get last balance
        double previous_balance = order.getLastUserBalance("wallet.txt", user_id);
        
        //status
        String order_status = "Placed";
        
        //initialize
        double total_bill = 0.0;
        
        //attribute
        double new_balance;
        
        //getting total bill
        try
        {
            customerorderhistorylist = dataloader.loadcustomerorderhistory("the_customer_order_history.txt");
            for (customer_order_history order_history : customerorderhistorylist)
            {
                if (order_history.getOrder_id().equalsIgnoreCase(order_id) && order_history.getUser_id().equalsIgnoreCase(user_id))
                {
                    total_bill = order_history.getOrder_amount();
                }
            }
        }catch (IOException ex) {
                System.out.println("Error writing to file: " + ex.getMessage());
                    }
        
        if (previous_balance >= total_bill)
        {
            try
        {
            //writing into cutomer order history
            customerorderhistorylist = dataloader.loadcustomerorderhistory("the_customer_order_history.txt");
            for (customer_order_history order_history : customerorderhistorylist)
            {
                if (order_history.getOrder_id().equalsIgnoreCase(order_id) && order_history.getUser_id().equalsIgnoreCase(user_id))
                {
                    new_balance = previous_balance - total_bill;
                    String entry = new_order_id +","+ order_history.getItem_name() +","+ order_history.getUser_id() +","+ time +","+ order_history.getOrder_amount() +","+ new_balance +","+ order_history.getAddress() +","+ order_history.getOrder_type() +","+ order_history.getVendor_name() +","+ order_status;
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter("the_customer_order_history.txt", true))) {
                        bw.write(entry); 
                        bw.newLine();
                    } catch (IOException ex) {
                System.out.println("Error writing to file: " + ex.getMessage());
                    }
                }
                
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
            
        //writing into order.txt
        try
        {
            orderlist = dataloader.loadorder("order.txt");
            for (order  orders : orderlist)
            {
                if (orders.getOrder_id().equalsIgnoreCase(order_id) && orders.getUser_id().equalsIgnoreCase(user_id))
                {
                    //o260619,c1,arab,falafel,7.0,Take away,Placed,7.0,06:35:17 2025-01-27,
                    String an_order = new_order_id +","+ orders.getUser_id() +","+ orders.getVendor_name() +","+ orders.getItem_name()+","+ orders.getItem_price() +","+ orders.getOrder_type() +","+ order_status +","+ orders.getTotal_bill() +","+ time +","+ orders.getAddress();
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter("order.txt", true))) 
                    {
                        bw.write(an_order); 
                        bw.newLine();
                    } catch (IOException ex) 
                    {
                        System.out.println("Error writing to file: " + ex.getMessage());
                    }
                }
                else
                {
                    System.out.println("Fix error");
                }
                
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        //writing into vendor order history
        try
        {
            vendorhistory = dataloader.loadvendorhistory("vendor_order_history.txt");
            for (vendor_order_history  vendororders : vendorhistory)
            {
                if (vendororders.getOrder_id().equalsIgnoreCase(order_id) && vendororders.getUser_id().equalsIgnoreCase(user_id))
                {
                    //o260619,c1,arab,falafel,7.0,Take away,Placed,7.0,06:35:17 2025-01-27,
                    String a_order = new_order_id +","+ vendororders.getUser_id() +","+ vendororders.getVendor_name() +","+ vendororders.getItem_name()+","+ vendororders.getItem_price() +","+ vendororders.getOrder_type() +","+ order_status +","+ vendororders.getTotal_bill() +","+ time +","+ vendororders.getAddress();
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter("vendor_order_history.txt", true))) 
                    {
                        bw.write(a_order); 
                        bw.newLine();
                    } catch (IOException ex) 
                    {
                        System.out.println("Error writing to file: " + ex.getMessage());
                    }
                }
                else
                {
                    System.out.println("Fix error");
                }
                
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
        
        //writing into wallet.txt
        try
        {
            transactions = dataloader.loadwallet("wallet.txt");
            for (wallet  transaction : transactions)
            {
                if (transaction.getOrder_id().equalsIgnoreCase(order_id) && transaction.getUser_id().equalsIgnoreCase(user_id))
                {
                    new_balance = previous_balance - total_bill;
                    String a_transaction = transaction.getUser_id() +","+ transaction.getTransaction_amount() +","+ transaction_id +","+ "deducted" +","+ new_balance +","+ new_order_id;
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter("wallet.txt", true))) {
                        bw.write(a_transaction); 
                        bw.newLine();
                    } catch (IOException ex) {
                System.out.println("Error writing to file: " + ex.getMessage());
                    }
                }
                
            }
        }catch (IOException ex) {
            ex.printStackTrace();
        }
            
        }
            
        
        
    }//GEN-LAST:event_btnorderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        customer c = new customer();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        topup tu = new topup();
        tu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnorder;
    private javax.swing.JButton btnshow;
    private javax.swing.JComboBox<String> cboorderid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblshow;
    // End of variables declaration//GEN-END:variables
}
