package final_assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author suhanashabhik
 */
public class RevenueCalculatorGUI extends javax.swing.JFrame {
    //private JTextArea DailyVendorEarningsTextArea, MonthlyVendorEarningsTextArea, YearlyVendorEarningsTextArea;
    //private JButton calculateButton;
    /**
     * Creates new form RevenueCalculatorGUI
     */
    public RevenueCalculatorGUI() {
        initComponents();
    }
public void calculateEarnings() {
    Map<String, Double> dailyEarningsMap = new HashMap<>();
    Map<String, Double> monthlyEarningsMap = new HashMap<>();
    Map<String, Double> yearlyEarningsMap = new HashMap<>();
 
    try {
        // Check if the file exists
        File file = new File("order.txt");
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "Order file not found.");
            return;
        }
 
        // Read the orders from the file
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line;
        DateFormat df = new SimpleDateFormat("HH:mm:ss yyyy-MM-dd");
 
        while ((line = br.readLine()) != null) {
            String[] order = line.split(",");
            if (order.length < 9) continue; // Ensure valid order format
 
            String orderStatus = order[6].trim();  // Order Status at index 6
            if (!orderStatus.equalsIgnoreCase("Placed")) continue; // Skip non-placed orders
 
            String orderDate = order[8].trim();  // Time and Date at index 8
            double totalBill = Double.parseDouble(order[7]); // Total Bill at index 7
 
            // Parse the order's date
            Date orderDateObj = df.parse(orderDate);
            Calendar cal = Calendar.getInstance();
            cal.setTime(orderDateObj);
 
            String dayKey = new SimpleDateFormat("yyyy-MM-dd").format(orderDateObj);
            String monthKey = new SimpleDateFormat("yyyy-MM").format(orderDateObj);
            String yearKey = new SimpleDateFormat("yyyy").format(orderDateObj);
 
            // Add earnings to maps
            dailyEarningsMap.put(dayKey, dailyEarningsMap.getOrDefault(dayKey, 0.0) + totalBill);
            monthlyEarningsMap.put(monthKey, monthlyEarningsMap.getOrDefault(monthKey, 0.0) + totalBill);
            yearlyEarningsMap.put(yearKey, yearlyEarningsMap.getOrDefault(yearKey, 0.0) + totalBill);
        }
        br.close();
 
        // Format and display earnings
        StringBuilder dailyEarningsDisplay = new StringBuilder();
        for (Map.Entry<String, Double> entry : dailyEarningsMap.entrySet()) {
            dailyEarningsDisplay.append(entry.getKey())
                                .append(": $")
                                .append(String.format("%.2f", entry.getValue()))
                                .append("\n");
        }
        DailyVendorEarningsTextArea.setText(dailyEarningsDisplay.toString());
 
        StringBuilder monthlyEarningsDisplay = new StringBuilder();
        for (Map.Entry<String, Double> entry : monthlyEarningsMap.entrySet()) {
            monthlyEarningsDisplay.append(entry.getKey())
                                  .append(": $")
                                  .append(String.format("%.2f", entry.getValue()))
                                  .append("\n");
        }
        MonthlyVendorEarningsTextArea.setText(monthlyEarningsDisplay.toString());
 
        StringBuilder yearlyEarningsDisplay = new StringBuilder();
        for (Map.Entry<String, Double> entry : yearlyEarningsMap.entrySet()) {
            yearlyEarningsDisplay.append(entry.getKey())
                                 .append(": $")
                                 .append(String.format("%.2f", entry.getValue()))
                                 .append("\n");
        }
        YearlyVendorEarningsTextArea.setText(yearlyEarningsDisplay.toString());
 
    } catch (IOException | ParseException ex) {
        JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DailyVendorEarningsTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        MonthlyVendorEarningsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        YearlyVendorEarningsTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 242, 244));

        jPanel1.setBackground(new java.awt.Color(151, 214, 207));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Revenue Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 242, 244));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Daily Earnings");

        DailyVendorEarningsTextArea.setColumns(20);
        DailyVendorEarningsTextArea.setRows(5);
        jScrollPane1.setViewportView(DailyVendorEarningsTextArea);

        MonthlyVendorEarningsTextArea.setColumns(20);
        MonthlyVendorEarningsTextArea.setRows(5);
        jScrollPane2.setViewportView(MonthlyVendorEarningsTextArea);

        YearlyVendorEarningsTextArea.setColumns(20);
        YearlyVendorEarningsTextArea.setRows(5);
        jScrollPane3.setViewportView(YearlyVendorEarningsTextArea);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Monthly Earnings");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Yearly Earnings");

        calculateButton.setBackground(new java.awt.Color(151, 214, 207));
        calculateButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(151, 214, 207));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(calculateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(calculateButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        calculateEarnings();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Navigate to "vendor_main.java"
        vendor_main vendorMainPage = new vendor_main();
        vendorMainPage.setVisible(true);
        this.dispose(); // Close current window
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Set the Look and Feel of the application to Nimbus
     // Set the Look and Feel of the application to Nimbus
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(RevenueCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    // Create and display the form in the Event Dispatch Thread
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new RevenueCalculatorGUI().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DailyVendorEarningsTextArea;
    private javax.swing.JTextArea MonthlyVendorEarningsTextArea;
    private javax.swing.JTextArea YearlyVendorEarningsTextArea;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
